apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
  labels:
    app: my-dashboard
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-dashboard
